export enum UserRole {
  ADMIN = 'ADMIN',
  RESPONSABLE_MAINTENANCE = 'RESPONSABLE_MAINTENANCE',
  TECHNICIEN = 'TECHNICIEN',
  DEMANDEUR = 'DEMANDEUR',
  MAGASINIER = 'MAGASINIER',
}

export enum Permission {
  // =========================
  // DASHBOARDS / RAPPORTS
  // =========================
  DASHBOARD_GENERAL_VIEW = 'DASHBOARD_GENERAL_VIEW',
  DASHBOARD_EQUIPEMENTS_VIEW = 'DASHBOARD_EQUIPEMENTS_VIEW',
  DASHBOARD_MAINTENANCE_VIEW = 'DASHBOARD_MAINTENANCE_VIEW',
  DASHBOARD_STOCK_VIEW = 'DASHBOARD_STOCK_VIEW',
  REPORTS_VIEW = 'REPORTS_VIEW',

  // =========================
  // ADMINISTRATION
  // =========================
  USERS_VIEW = 'USERS_VIEW',
  USERS_CREATE = 'USERS_CREATE',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DISABLE = 'USERS_DISABLE',
  USERS_DELETE = 'USERS_DELETE',

  ROLES_VIEW = 'ROLES_VIEW',
  ROLES_MANAGE = 'ROLES_MANAGE',

  PRIVILEGES_VIEW = 'PRIVILEGES_VIEW',
  PRIVILEGES_MANAGE = 'PRIVILEGES_MANAGE',

  SYSTEM_CONFIG = 'SYSTEM_CONFIG',

  // =========================
  // ÉQUIPEMENTS
  // =========================
  EQUIPEMENTS_VIEW = 'EQUIPEMENTS_VIEW',

  MATERIEL_VIEW = 'MATERIEL_VIEW',
  MATERIEL_CREATE = 'MATERIEL_CREATE',
  MATERIEL_UPDATE = 'MATERIEL_UPDATE',
  MATERIEL_DELETE = 'MATERIEL_DELETE',
  MATERIEL_RESTORE = 'MATERIEL_RESTORE',

  MODELE_VIEW = 'MODELE_VIEW',
  MODELE_CREATE = 'MODELE_CREATE',
  MODELE_UPDATE = 'MODELE_UPDATE',
  MODELE_DELETE = 'MODELE_DELETE',

  ARBORESCENCE_VIEW = 'ARBORESCENCE_VIEW',
  ARBORESCENCE_MANAGE = 'ARBORESCENCE_MANAGE',

  POINT_STRUCTURE_VIEW = 'POINT_STRUCTURE_VIEW',
  POINT_STRUCTURE_CREATE = 'POINT_STRUCTURE_CREATE',
  POINT_STRUCTURE_UPDATE = 'POINT_STRUCTURE_UPDATE',
  POINT_STRUCTURE_DELETE = 'POINT_STRUCTURE_DELETE',

  POINT_MESURE_VIEW = 'POINT_MESURE_VIEW',
  POINT_MESURE_CREATE = 'POINT_MESURE_CREATE',
  POINT_MESURE_UPDATE = 'POINT_MESURE_UPDATE',
  POINT_MESURE_DELETE = 'POINT_MESURE_DELETE',

  RELEVE_MESURE_VIEW = 'RELEVE_MESURE_VIEW',
  RELEVE_MESURE_CREATE = 'RELEVE_MESURE_CREATE',
  RELEVE_MESURE_UPDATE = 'RELEVE_MESURE_UPDATE',
  RELEVE_MESURE_DELETE = 'RELEVE_MESURE_DELETE',

  FAMILLE_VIEW = 'FAMILLE_VIEW',
  FAMILLE_MANAGE = 'FAMILLE_MANAGE',

  FABRICANT_VIEW = 'FABRICANT_VIEW',
  FABRICANT_MANAGE = 'FABRICANT_MANAGE',

  MARQUE_VIEW = 'MARQUE_VIEW',
  MARQUE_MANAGE = 'MARQUE_MANAGE',

  TYPE_EQUIPEMENT_VIEW = 'TYPE_EQUIPEMENT_VIEW',
  TYPE_EQUIPEMENT_MANAGE = 'TYPE_EQUIPEMENT_MANAGE',

  ETAT_MODELE_VIEW = 'ETAT_MODELE_VIEW',
  ETAT_MODELE_MANAGE = 'ETAT_MODELE_MANAGE',

  // =========================
  // MAINTENANCE
  // =========================
  MAINTENANCE_VIEW = 'MAINTENANCE_VIEW',

  DI_VIEW_ALL = 'DI_VIEW_ALL',
  DI_VIEW_OWN = 'DI_VIEW_OWN',
  DI_CREATE = 'DI_CREATE',
  DI_UPDATE = 'DI_UPDATE',
  DI_SUBMIT = 'DI_SUBMIT',
  DI_ACCEPT = 'DI_ACCEPT',
  DI_REFUSE = 'DI_REFUSE',
  DI_VALIDATE_WORKS = 'DI_VALIDATE_WORKS',
  DI_CLOSE = 'DI_CLOSE',
  DI_DELETE = 'DI_DELETE',

  INTERVENTION_VIEW_ALL = 'INTERVENTION_VIEW_ALL',
  INTERVENTION_VIEW_ASSIGNED = 'INTERVENTION_VIEW_ASSIGNED',
  INTERVENTION_CREATE = 'INTERVENTION_CREATE',
  INTERVENTION_UPDATE = 'INTERVENTION_UPDATE',
  INTERVENTION_PLANIFY = 'INTERVENTION_PLANIFY',
  INTERVENTION_ASSIGN = 'INTERVENTION_ASSIGN',
  INTERVENTION_START = 'INTERVENTION_START',
  INTERVENTION_REPORT = 'INTERVENTION_REPORT',
  INTERVENTION_COMPLETE = 'INTERVENTION_COMPLETE',
  INTERVENTION_CLOSE = 'INTERVENTION_CLOSE',
  INTERVENTION_CANCEL = 'INTERVENTION_CANCEL',
  INTERVENTION_DELETE = 'INTERVENTION_DELETE',

  GAMME_VIEW = 'GAMME_VIEW',
  GAMME_CREATE = 'GAMME_CREATE',
  GAMME_UPDATE = 'GAMME_UPDATE',
  GAMME_DELETE = 'GAMME_DELETE',

  PLAN_PREVENTIF_VIEW = 'PLAN_PREVENTIF_VIEW',
  PLAN_PREVENTIF_CREATE = 'PLAN_PREVENTIF_CREATE',
  PLAN_PREVENTIF_UPDATE = 'PLAN_PREVENTIF_UPDATE',
  PLAN_PREVENTIF_DELETE = 'PLAN_PREVENTIF_DELETE',
  PLAN_PREVENTIF_GENERATE_INTERVENTIONS = 'PLAN_PREVENTIF_GENERATE_INTERVENTIONS',

  PLAN_PREVENTIF_PREDEFINI_VIEW = 'PLAN_PREVENTIF_PREDEFINI_VIEW',
  PLAN_PREVENTIF_PREDEFINI_CREATE = 'PLAN_PREVENTIF_PREDEFINI_CREATE',
  PLAN_PREVENTIF_PREDEFINI_UPDATE = 'PLAN_PREVENTIF_PREDEFINI_UPDATE',
  PLAN_PREVENTIF_PREDEFINI_DELETE = 'PLAN_PREVENTIF_PREDEFINI_DELETE',

  HISTORIQUE_PREVENTIF_VIEW = 'HISTORIQUE_PREVENTIF_VIEW',

  // =========================
  // STOCK
  // =========================
  STOCK_VIEW = 'STOCK_VIEW',

  ARTICLE_VIEW = 'ARTICLE_VIEW',
  ARTICLE_CREATE = 'ARTICLE_CREATE',
  ARTICLE_UPDATE = 'ARTICLE_UPDATE',
  ARTICLE_DELETE = 'ARTICLE_DELETE',
  ARTICLE_RESTORE = 'ARTICLE_RESTORE',

  UNITE_ARTICLE_VIEW = 'UNITE_ARTICLE_VIEW',
  UNITE_ARTICLE_MANAGE = 'UNITE_ARTICLE_MANAGE',

  MAGASIN_VIEW = 'MAGASIN_VIEW',
  MAGASIN_CREATE = 'MAGASIN_CREATE',
  MAGASIN_UPDATE = 'MAGASIN_UPDATE',
  MAGASIN_DELETE = 'MAGASIN_DELETE',

  EMPLACEMENT_VIEW = 'EMPLACEMENT_VIEW',
  EMPLACEMENT_MANAGE = 'EMPLACEMENT_MANAGE',

  ENTREE_STOCK_VIEW = 'ENTREE_STOCK_VIEW',
  ENTREE_STOCK_CREATE = 'ENTREE_STOCK_CREATE',
  ENTREE_STOCK_VALIDATE = 'ENTREE_STOCK_VALIDATE',
  ENTREE_STOCK_CANCEL = 'ENTREE_STOCK_CANCEL',

  SORTIE_STOCK_VIEW = 'SORTIE_STOCK_VIEW',
  SORTIE_STOCK_CREATE = 'SORTIE_STOCK_CREATE',
  SORTIE_STOCK_VALIDATE = 'SORTIE_STOCK_VALIDATE',
  SORTIE_STOCK_CANCEL = 'SORTIE_STOCK_CANCEL',

  MOUVEMENT_STOCK_VIEW = 'MOUVEMENT_STOCK_VIEW',

  RESERVATION_VIEW = 'RESERVATION_VIEW',
  RESERVATION_CREATE = 'RESERVATION_CREATE',
  RESERVATION_UPDATE = 'RESERVATION_UPDATE',
  RESERVATION_VALIDATE = 'RESERVATION_VALIDATE',
  RESERVATION_CANCEL = 'RESERVATION_CANCEL',

  DEMANDE_TRANSFERT_VIEW = 'DEMANDE_TRANSFERT_VIEW',
  DEMANDE_TRANSFERT_CREATE = 'DEMANDE_TRANSFERT_CREATE',
  DEMANDE_TRANSFERT_VALIDATE = 'DEMANDE_TRANSFERT_VALIDATE',
  DEMANDE_TRANSFERT_EXECUTE = 'DEMANDE_TRANSFERT_EXECUTE',
  DEMANDE_TRANSFERT_CANCEL = 'DEMANDE_TRANSFERT_CANCEL',

  REAPPROVISIONNEMENT_VIEW = 'REAPPROVISIONNEMENT_VIEW',
  REAPPROVISIONNEMENT_CREATE = 'REAPPROVISIONNEMENT_CREATE',
  REAPPROVISIONNEMENT_UPDATE = 'REAPPROVISIONNEMENT_UPDATE',
  REAPPROVISIONNEMENT_VALIDATE = 'REAPPROVISIONNEMENT_VALIDATE',
  REAPPROVISIONNEMENT_CANCEL = 'REAPPROVISIONNEMENT_CANCEL',

  INVENTAIRE_VIEW = 'INVENTAIRE_VIEW',
  INVENTAIRE_CREATE = 'INVENTAIRE_CREATE',
  INVENTAIRE_UPDATE = 'INVENTAIRE_UPDATE',
  INVENTAIRE_VALIDATE = 'INVENTAIRE_VALIDATE',
  INVENTAIRE_CLOSE = 'INVENTAIRE_CLOSE',

  INVENTAIRE_PREPARE_VIEW = 'INVENTAIRE_PREPARE_VIEW',
  INVENTAIRE_PREPARE_CREATE = 'INVENTAIRE_PREPARE_CREATE',
  INVENTAIRE_PREPARE_UPDATE = 'INVENTAIRE_PREPARE_UPDATE',
  INVENTAIRE_PREPARE_DELETE = 'INVENTAIRE_PREPARE_DELETE',
  INVENTAIRE_PREPARE_LAUNCH = 'INVENTAIRE_PREPARE_LAUNCH',

  STOCK_CONSUMPTION_DECLARE = 'STOCK_CONSUMPTION_DECLARE',
  STOCK_CONSUMPTION_VIEW = 'STOCK_CONSUMPTION_VIEW',

  // =========================
  // ALIAS ANCIENS NOMS DEV V0
  // pour ne pas casser ton frontend actuel
  // =========================
  VIEW_DASHBOARD = 'DASHBOARD_GENERAL_VIEW',
  VIEW_MATERIALS = 'EQUIPEMENTS_VIEW',
  CREATE_MATERIAL = 'MATERIEL_CREATE',
  EDIT_MATERIAL = 'MATERIEL_UPDATE',
  DELETE_MATERIAL = 'MATERIEL_DELETE',

  VIEW_MAINTENANCE = 'MAINTENANCE_VIEW',
  CREATE_DI = 'DI_CREATE',
  EDIT_DI = 'DI_UPDATE',
  VIEW_INTERVENTIONS = 'INTERVENTION_VIEW_ALL',
  CREATE_INTERVENTION = 'INTERVENTION_CREATE',
  EDIT_INTERVENTION = 'INTERVENTION_UPDATE',

  VIEW_STOCK = 'STOCK_VIEW',
  CREATE_ENTRY = 'ENTREE_STOCK_CREATE',
  CREATE_EXIT = 'SORTIE_STOCK_CREATE',
  VIEW_INVENTORY = 'INVENTAIRE_VIEW',
  EDIT_INVENTORY = 'INVENTAIRE_UPDATE',

  MANAGE_USERS = 'USERS_VIEW',
  MANAGE_ROLES = 'ROLES_MANAGE',
  VIEW_REPORTS = 'REPORTS_VIEW',
}

export type User = {
  id: string;
  email: string;
  fullName: string;
  role: UserRole;
  permissions: Permission[];
  avatar?: string | null;
  createdAt?: string;
};

export type LoginCredentials = {
  email: string;
  password: string;
};

export type LoginResponse = {
  user: User;
  token: string;
};

export type AuthContextType = {
  user: User | null;
  isLoading: boolean;
  isAuthenticated: boolean;
  login: (credentials: LoginCredentials) => Promise<void>;
  logout: () => void;
  hasPermission: (permission: Permission | Permission[]) => boolean;
  hasRole: (role: UserRole | UserRole[]) => boolean;
  hasAnyRole: (roles: UserRole[]) => boolean;
};